name: Actions Workflow

on:
  push:
    push:
      branches:
        - master
        - 'feature/*'
        - 'feature/**'
        - '!feature/featC'
      tags:
        - v1.*
      paths:
        - '**.js'
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run:
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Matt
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
